### ISSUE TITLE
Readme: the explanation of Corrective policies is hard to understand

### ISSUE THREAD

**Issue by yellowbrickc** [ddd-crew/aggregate-design-canvas#2]
Hi @cakper ,

I think this sentence is really hard to grasp (unfortunately I cannot link the exact lines here) and maybe we could reformulate it somehow:
`Corrective policies are the ones, that the aggregate is involved with because you’ve made an explicit tradeoff to give up some invariants.`
[5. Corrective Policies](https://github.com/ddd-crew/aggregate-design-canvas/blob/master/README.md#4-enforced-invariants--5-corrective-policies)

**Comment by cakper** [comment]
Hi @yellowbrickc! Thank you for your feedback. How about this:

> 4. Enforced Invariants & 5. Corrective Policies

> One of the main jobs of the aggregate is to enforce business invariants. These invariants protect business logic and listing the main ones in this section will make sure that you agree on the responsibilities that the aggregate has. A large number of enforced invariants can indicate high local complexity of the aggregate implementation.

> If you decide to change the boundaries of the aggregate and relax some of the invariants (for example to reduce the chance of concurrency conflict), then some extra business logic might be required to correct some of the inconsistencies. In the context of this canvas, we call this logic corrective policies. A large number of such policies might indicate that the business logic was pushed outside of the aggregate, which can increase the complexity of implementation.

> Listing on the canvas both Invariants and Corrective Policies will make design trade-offs explicit and will help you decide whether the boundaries you decided on are useful or not.

**Comment by yellowbrickc** [comment]
Yes, thank you! Now I can see, what you mean!

**Comment by cakper** [comment]
PR is ready: https://github.com/ddd-crew/aggregate-design-canvas/pull/4

**Comment by yellowbrickc** [comment]
Review ready :)

**Comment by cakper** [comment]
Resolved in: https://github.com/ddd-crew/aggregate-design-canvas/pull/4
