### ISSUE TITLE
Explanation of Size 

### ISSUE THREAD

**Issue by yellowbrickc** [ddd-crew/aggregate-design-canvas#3]
In [9. Size](https://github.com/ddd-crew/aggregate-design-canvas/blob/master/README.md#9-size) is a confusing explanation: what is more relevant, the number of the events or the size of the events?
`In this case the size itself is being measured in the number of events per aggregate instance. In some domains events are smaller, and in others much larger, so please remember about it during evaluation.`

**Comment by cakper** [comment]
Hello @yellowbrickc! This is a good question, as what is relevant is the combination of both and the way you model your system will impact this estimate. E.g. you can have a single event that aggregates multiple smaller ones, and it's going to be big. Or you can have multiple smaller ones. I've tried to improve the explanation here: https://github.com/ddd-crew/aggregate-design-canvas/pull/5

**Comment by yellowbrickc** [comment]
Sorry for the delay, my last days were very busy. I think the example you have added makes everything clearer 👍
